DROP TABLE IF EXISTS BANK_ACCT CASCADE;
DROP TABLE IF EXISTS CUST_PROFILE CASCADE;

CREATE TABLE CUST_PROFILE
(
	ID			BIGINT(20) NOT NULL AUTO_INCREMENT,
	FIRST_NM	VARCHAR(255) NOT NULL,
    LAST_NM		VARCHAR(100) NOT NULL,
	EMAIL		VARCHAR(300) NOT NULL,
    PHONE_NUM	VARCHAR(15) NOT NULL,
    MAIL_ADDR_1	VARCHAR(120) NOT NULL,
    MAIL_ADDR_2	VARCHAR(120) NOT NULL,
	IS_ACTIVE	CHAR(1) NOT NULL,
	IS_DELETE	CHAR(1) NOT NULL,
	CREATE_TMS	TIMESTAMP NOT NULL,
	UPDATE_TMS	TIMESTAMP NOT NULL,
	CREATED_BY	VARCHAR(50) NOT NULL,
	UPDATED_BY	VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_CUST_PF_ID` PRIMARY KEY (ID)
);

CREATE TABLE BANK_ACCT
(
	ID				BIGINT(20) NOT NULL AUTO_INCREMENT,
	ACCT_NUM		VARCHAR(50) NOT NULL,
	ACCT_BAL		DECIMAL(11,2) NOT NULL,
    CUST_ID			BIGINT(20) NOT NULL,
	IS_ACTIVE		CHAR(1) NOT NULL,
	IS_DELETE		CHAR(1) NOT NULL,
	CREATE_TMS		TIMESTAMP NOT NULL,
	UPDATE_TMS		TIMESTAMP NOT NULL,
	CREATED_BY		VARCHAR(50) NOT NULL,
	UPDATED_BY		VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_BNK_ACCT_ID` PRIMARY KEY (ID),
	CONSTRAINT `FK_BNK_ACCT_CUST_ID` FOREIGN KEY (CLIENT_ID) REFERENCES CUST_PROFILE(ID)
);